version: "3.7"
services:
  redis:
    image: redis:6.2
    container_name: redis
    command: redis-server --requirepass admin
    ports:
      - 6379:6379
    deploy:
      restart_policy:
        condition: on-failure
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    deploy:
      placement:
        constraints: [ node.role == manager ]
  mongodb:
    image: mongo:bionic
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3.8.14-management
    container_name: rabbitmq
    restart: always
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin